get http://localhost:3000 HTTP/1.1
###
get http://localhost:3000/users HTTP/1.1

###
get http://localhost:3000/users/2 HTTP/1.1

###
post http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "username": "echavira",
    "first_name": "Chaviris",
    "last_name": "Chavez",
    "phone": "44i95553",
    "email": "echaviris@esquimal.mx",
    "role_id": 1
}

###
PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json

{
    "username": "rksadkj",
    "first_name": "Chayo",
    "last_name": "Montelongo",
    "phone": "44i9555sdasd<sdas3",
    "email": "viris@esquimal.mx"
}

###
DELETE http://localhost:3000/users/5 HTTP/1.1